name: Automate Upstream changes (main) into development (dev) workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Create Unique Branch Name"
        run: |
          echo "BUILD_DATE=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_OUTPUT

        id: version

      - name: open PR main-sync -> dev
        run: |
          git branch main-sync-${{ steps.version.outputs.BUILD_DATE }}
          git checkout main-sync-${{ steps.version.outputs.BUILD_DATE }}
          git push origin main-sync-${{ steps.version.outputs.BUILD_DATE }}
          gh pr create --base dev --head main-sync-${{ steps.version.outputs.BUILD_DATE }} --title "Automated PR" --body "Automated PR to merge in any changes committed from main into dev" 
          gh pr merge --merge

        env:
          GH_TOKEN: ${{ github.token }}
