name: Open PR to merge upstream changes (main) into development workflow (dev)

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: pull-request
        run: |
          gh_pr_up() { gh pr create $* || gh pr edit $* }
          gh_pr_up --title "My pull request" --body "Description"
