name: Automate Upstream changes (main) into development (dev) workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if branch exists
        id: check-branch-exists
        uses: GuillaumeFalourd/branch-exists@v1
        with:
          branch: main-sync

      - name: open PR main-sync -> dev
        run: |
          if ${{ steps.check-branch-exists.outputs.exists == 'true' }}; then
            echo "Branch exists"
            git fetch origin main-sync  # Fetch the latest commits from main-sync branch
            git checkout main-sync
            git merge origin/main
            git push origin main-sync
            gh pr merge --auto --merge
          else

            echo "Branch does not exist"
            git branch main-sync
            git checkout main-sync
            git push origin main-sync
            gh pr create --base dev --head main-sync --title "Automated PR" --body "Automated PR" 
          fi

        env:
          GH_TOKEN: ${{ github.token }}
# gh pr merge --merge
