name: Open PR to merge upstream changes (main) into development workflow (dev)

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: open PR
        run: |
          gh pr create --fill
