name: Open PR to merge upstream changes (main) into development workflow (dev)

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions: # This is required to allow the action to create a PR
  pull-requests: write

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: open PR
        run: |
          gh pr create --base dev --title "Upstream changes" --body "Merging upstream changes into development workflow" --repo ${{ github.repository }} --assignee @me --label "automerge"
        env:
          GH_TOKEN: ${{ github.token }}
