name: Automate Upstream changes (main) into development (dev) workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: open PR main-sync -> dev
          echo "BRANCH_NAME=main-sync" >> $GITHUB_ENV
        run: |
          git branch ${{ env.BRANCH_NAME }}
          git checkout ${{ env.BRANCH_NAME }}
          git push origin ${{ env.BRANCH_NAME }}
          gh pr create --base dev --head ${{ env.BRANCH_NAME }} --title "Automated PR" --body "Automated PR"  # Open a pull request

        env:
          GH_TOKEN: ${{ github.token }}
# gh pr merge --merge
