name: Automate Upstream changes (main) into development (dev) workflow

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: open PR
        run: |
          gh pr create --base dev --title "Automated PR" --body "Automated PR"
          gh pr --merge
        env:
          GH_TOKEN: ${{ github.token }}
